### ISSUE TITLE
误报率过高。。。。

### ISSUE THREAD

**Issue by Ludovicofu** [carl1l/f403#3]
。。。。。。

**Comment by carl1l** [comment]
误报率过高是体现在什么方面？

**Comment by Ludovicofu** [comment]
根据响应内容作出绕过分析这一块，估计有问题，手动可以，用工具就不行了，就修改get请求方式为post

**Comment by carl1l** [comment]
麻烦师傅能举一个具体的场景么我好定位下问题，工具就是单纯发包进行fuzz，也没有什么根据响应内容做出绕过分析啥的

**Comment by Ludovicofu** [comment]
GET /exam/api/sys/config/detail HTTP/1.1
Host: 114.215.203.73
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
Content-Length: 14
Accept: application/json, text/plain, */*
Accept-Language: zh-CN,zh;q=0.9
Content-Type: application/json;charset=UTF-8
Origin: http://114.215.203.73
Referer: http://114.215.203.73/
Accept-Encoding: gzip

{"id":"1"}
请求方式改为post就能越过，但工具就。。。。

**Comment by carl1l** [comment]
明白师傅的意思了，目前工具暂没有添加post数据的功能，后期会加上，感谢师傅提交的issue
